# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.event_manager:
        class: AppBundle\Utils\Event\EventManager
    
    appbundle.registration.form.type:
        class: AppBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: appbundle_user_registration }
            
    my_user_provider:
        class: AppBundle\Security\Core\User\FOSUBUserProvider
        arguments: [@fos_user.user_manager, {facebook: facebook_id}]