<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Event;
use AppBundle\Entity\User;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository {

    public function findTheClosest($latitude, $longitude, $distance) {
        $latitude = (double)$latitude;
        $longitude = (double)$longitude;
        $distance = (double)$distance;
        
        $queryBuilder = $this->getEntityManager()->getConnection()->createQueryBuilder();
        $queryBuilder
                ->select('id', 'isPublic', 'name', 'description', 'startDate', 'endDate', 'maxMembersNumber', 'endRegistrationDate', 'address', '(6371 * acos( cos( radians( :latitude ) ) * cos( radians( latitude ) ) * cos( radians( longitude ) - radians( :longitude ) ) + sin( radians( :latitude ) ) * sin( radians( latitude ) ) )) AS distance')
                ->from('Event', 'e')
                ->having('distance < :distance')
                ->setParameters(array(
                    'longitude' => $longitude,
                    'latitude' => $latitude,
                    'distance' => $distance
                ));

        
        $events = $queryBuilder->execute()->fetchAll();
        
        return $events;
    }

}
