<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Event;
use AppBundle\Entity\User;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function isUserJoinedToEvent(User $user, Event $event) {
        foreach($event->getJoinedUsers() as $member) {
            if($member->getId() === $user->getId()) {
                return true;
            }
        }
        return false;
    }
}
